package dev.andface.galaxy.feature

enum class FeatureGroup {
    UPPER_FACE,
    MID_FACE,
    LOWER_FACE,
    EYE,
    POSE,
    GLOBAL
}

enum class FeatureType(
    val label: String,
    val group: FeatureGroup,
    val ruleWeight: Double,
    val minimumSigma: Double
) {
    EyeDistance("EyeDistance", FeatureGroup.UPPER_FACE, 0.94, 0.012),
    BrowDistance("BrowDistance", FeatureGroup.UPPER_FACE, 0.86, 0.014),
    NoseWidth("NoseWidth", FeatureGroup.MID_FACE, 0.91, 0.012),
    NoseToChin("NoseToChin", FeatureGroup.LOWER_FACE, 0.78, 0.016),
    MouthWidth("MouthWidth", FeatureGroup.LOWER_FACE, 0.74, 0.018),
    JawWidth("JawWidth", FeatureGroup.LOWER_FACE, 0.78, 0.018),
    LeftEyeOpen("LeftEyeOpen", FeatureGroup.EYE, 0.76, 0.020),
    RightEyeOpen("RightEyeOpen", FeatureGroup.EYE, 0.76, 0.020),
    NoseToMouth("NoseToMouth", FeatureGroup.LOWER_FACE, 0.76, 0.016),
    FaceAspect("FaceAspect", FeatureGroup.GLOBAL, 0.82, 0.018),
    Yaw("Yaw", FeatureGroup.POSE, 0.70, 0.060),
    Pitch("Pitch", FeatureGroup.POSE, 0.70, 0.060),
    Roll("Roll", FeatureGroup.POSE, 0.70, 0.050),

    InnerEyeDistance("InnerEyeDistance", FeatureGroup.UPPER_FACE, 0.88, 0.012),
    LeftEyeWidth("LeftEyeWidth", FeatureGroup.EYE, 0.72, 0.014),
    RightEyeWidth("RightEyeWidth", FeatureGroup.EYE, 0.72, 0.014),
    EyeOpenAsymmetry("EyeOpenAsymmetry", FeatureGroup.EYE, 0.62, 0.016),
    BrowWidth("BrowWidth", FeatureGroup.UPPER_FACE, 0.72, 0.014),
    BrowAsymmetry("BrowAsymmetry", FeatureGroup.UPPER_FACE, 0.60, 0.016),
    NoseBridgeLength("NoseBridgeLength", FeatureGroup.MID_FACE, 0.76, 0.014),
    EyeNoseLeft("EyeNoseLeft", FeatureGroup.MID_FACE, 0.78, 0.014),
    EyeNoseRight("EyeNoseRight", FeatureGroup.MID_FACE, 0.78, 0.014),
    EyeNoseSymmetry("EyeNoseSymmetry", FeatureGroup.MID_FACE, 0.65, 0.016),
    UpperFaceWidth("UpperFaceWidth", FeatureGroup.UPPER_FACE, 0.76, 0.014),
    CheekboneWidth("CheekboneWidth", FeatureGroup.MID_FACE, 0.80, 0.014),
    LeftCheekNose("LeftCheekNose", FeatureGroup.MID_FACE, 0.74, 0.014),
    RightCheekNose("RightCheekNose", FeatureGroup.MID_FACE, 0.74, 0.014),
    CheekNoseSymmetry("CheekNoseSymmetry", FeatureGroup.MID_FACE, 0.60, 0.016),
    LeftBrowEyeGap("LeftBrowEyeGap", FeatureGroup.UPPER_FACE, 0.70, 0.014),
    RightBrowEyeGap("RightBrowEyeGap", FeatureGroup.UPPER_FACE, 0.70, 0.014),
    BrowEyeGapAsymmetry("BrowEyeGapAsymmetry", FeatureGroup.UPPER_FACE, 0.58, 0.016),
    LeftUnderEyeCheek("LeftUnderEyeCheek", FeatureGroup.MID_FACE, 0.70, 0.014),
    RightUnderEyeCheek("RightUnderEyeCheek", FeatureGroup.MID_FACE, 0.70, 0.014),
    UnderEyeCheekAsymmetry("UnderEyeCheekAsymmetry", FeatureGroup.MID_FACE, 0.58, 0.016),

    InterBrowDistance("InterBrowDistance", FeatureGroup.UPPER_FACE, 0.66, 0.014),
    LeftBrowNoseRoot("LeftBrowNoseRoot", FeatureGroup.MID_FACE, 0.64, 0.014),
    RightBrowNoseRoot("RightBrowNoseRoot", FeatureGroup.MID_FACE, 0.64, 0.014),
    BrowNoseRootAsymmetry("BrowNoseRootAsymmetry", FeatureGroup.MID_FACE, 0.52, 0.016),
    LeftInnerEyeNoseRoot("LeftInnerEyeNoseRoot", FeatureGroup.MID_FACE, 0.66, 0.014),
    RightInnerEyeNoseRoot("RightInnerEyeNoseRoot", FeatureGroup.MID_FACE, 0.66, 0.014),
    InnerEyeNoseRootAsymmetry("InnerEyeNoseRootAsymmetry", FeatureGroup.MID_FACE, 0.52, 0.016),
    LeftTempleEye("LeftTempleEye", FeatureGroup.UPPER_FACE, 0.62, 0.014),
    RightTempleEye("RightTempleEye", FeatureGroup.UPPER_FACE, 0.62, 0.014),
    TempleEyeAsymmetry("TempleEyeAsymmetry", FeatureGroup.UPPER_FACE, 0.50, 0.016),
    EyeWidthAsymmetry("EyeWidthAsymmetry", FeatureGroup.EYE, 0.56, 0.016),
    LeftBrowSlope("LeftBrowSlope", FeatureGroup.UPPER_FACE, 0.48, 0.020),
    RightBrowSlope("RightBrowSlope", FeatureGroup.UPPER_FACE, 0.48, 0.020),
    BrowSlopeAsymmetry("BrowSlopeAsymmetry", FeatureGroup.UPPER_FACE, 0.42, 0.020),
    LeftEyeHeight("LeftEyeHeight", FeatureGroup.EYE, 0.62, 0.012),
    RightEyeHeight("RightEyeHeight", FeatureGroup.EYE, 0.62, 0.012),
    EyeHeightAsymmetry("EyeHeightAsymmetry", FeatureGroup.EYE, 0.48, 0.016),
    LeftBrowWidth("LeftBrowWidth", FeatureGroup.UPPER_FACE, 0.58, 0.014),
    RightBrowWidth("RightBrowWidth", FeatureGroup.UPPER_FACE, 0.58, 0.014),
    LeftBrowOuterEyeGap("LeftBrowOuterEyeGap", FeatureGroup.UPPER_FACE, 0.56, 0.014),
    RightBrowOuterEyeGap("RightBrowOuterEyeGap", FeatureGroup.UPPER_FACE, 0.56, 0.014),
    BrowOuterGapAsymmetry("BrowOuterGapAsymmetry", FeatureGroup.UPPER_FACE, 0.44, 0.016),
    LeftBrowInnerEyeGap("LeftBrowInnerEyeGap", FeatureGroup.UPPER_FACE, 0.56, 0.014),
    RightBrowInnerEyeGap("RightBrowInnerEyeGap", FeatureGroup.UPPER_FACE, 0.56, 0.014),
    BrowInnerGapAsymmetry("BrowInnerGapAsymmetry", FeatureGroup.UPPER_FACE, 0.44, 0.016),
    NoseRootToBrowLine("NoseRootToBrowLine", FeatureGroup.MID_FACE, 0.54, 0.014),
    ForeheadToEyeLine("ForeheadToEyeLine", FeatureGroup.UPPER_FACE, 0.52, 0.016),
    UpperFaceAspect("UpperFaceAspect", FeatureGroup.UPPER_FACE, 0.52, 0.018),
    LeftBrowEyeDistance("LeftBrowEyeDistance", FeatureGroup.EYE, 0.52, 0.014),
    RightBrowEyeDistance("RightBrowEyeDistance", FeatureGroup.EYE, 0.52, 0.014),
    BrowEyeDistanceAsymmetry("BrowEyeDistanceAsymmetry", FeatureGroup.EYE, 0.40, 0.016),
    NoseRootEyeLineDistance("NoseRootEyeLineDistance", FeatureGroup.MID_FACE, 0.50, 0.014),
    NoseTipEyeLineDistance("NoseTipEyeLineDistance", FeatureGroup.MID_FACE, 0.54, 0.014),
    NoseLateralOffset("NoseLateralOffset", FeatureGroup.MID_FACE, 0.44, 0.018),
    LeftPeriocularArea("LeftPeriocularArea", FeatureGroup.EYE, 0.44, 0.014),
    RightPeriocularArea("RightPeriocularArea", FeatureGroup.EYE, 0.44, 0.014),
    PeriocularAreaAsymmetry("PeriocularAreaAsymmetry", FeatureGroup.EYE, 0.36, 0.016),
    LeftMidFaceTriangle("LeftMidFaceTriangle", FeatureGroup.MID_FACE, 0.50, 0.014),
    RightMidFaceTriangle("RightMidFaceTriangle", FeatureGroup.MID_FACE, 0.50, 0.014),
    MidFaceTriangleAsymmetry("MidFaceTriangleAsymmetry", FeatureGroup.MID_FACE, 0.38, 0.016),
    LeftNoseWing("LeftNoseWing", FeatureGroup.MID_FACE, 0.48, 0.014),
    RightNoseWing("RightNoseWing", FeatureGroup.MID_FACE, 0.48, 0.014),
    NoseWingAsymmetry("NoseWingAsymmetry", FeatureGroup.MID_FACE, 0.36, 0.016),
    NoseBaseTriangle("NoseBaseTriangle", FeatureGroup.MID_FACE, 0.42, 0.014),
    MouthHeight("MouthHeight", FeatureGroup.LOWER_FACE, 0.52, 0.014),
    MouthAspect("MouthAspect", FeatureGroup.LOWER_FACE, 0.46, 0.016),
    ChinMouthDistance("ChinMouthDistance", FeatureGroup.LOWER_FACE, 0.52, 0.016),
    ChinJawOffset("ChinJawOffset", FeatureGroup.LOWER_FACE, 0.40, 0.018),
    LeftUpperMidfaceArea("LeftUpperMidfaceArea", FeatureGroup.MID_FACE, 0.44, 0.014),
    RightUpperMidfaceArea("RightUpperMidfaceArea", FeatureGroup.MID_FACE, 0.44, 0.014),
    UpperMidfaceAreaAsymmetry("UpperMidfaceAreaAsymmetry", FeatureGroup.MID_FACE, 0.34, 0.016),
    LeftNoseCheekArea("LeftNoseCheekArea", FeatureGroup.MID_FACE, 0.42, 0.014),
    RightNoseCheekArea("RightNoseCheekArea", FeatureGroup.MID_FACE, 0.42, 0.014),
    NoseCheekAreaAsymmetry("NoseCheekAreaAsymmetry", FeatureGroup.MID_FACE, 0.34, 0.016),
    LeftTempleCheekSlope("LeftTempleCheekSlope", FeatureGroup.UPPER_FACE, 0.36, 0.035),
    RightTempleCheekSlope("RightTempleCheekSlope", FeatureGroup.UPPER_FACE, 0.36, 0.035),
    TempleCheekSlopeAsymmetry("TempleCheekSlopeAsymmetry", FeatureGroup.UPPER_FACE, 0.30, 0.030),
    MidfaceWidthRatio("MidfaceWidthRatio", FeatureGroup.MID_FACE, 0.42, 0.025),
    LeftBrowArchHeight("LeftBrowArchHeight", FeatureGroup.UPPER_FACE, 0.40, 0.018),
    RightBrowArchHeight("RightBrowArchHeight", FeatureGroup.UPPER_FACE, 0.40, 0.018),
    BrowArchAsymmetry("BrowArchAsymmetry", FeatureGroup.UPPER_FACE, 0.32, 0.018),
    BrowLineTilt("BrowLineTilt", FeatureGroup.UPPER_FACE, 0.32, 0.020),
    LeftEyeCornerTilt("LeftEyeCornerTilt", FeatureGroup.EYE, 0.38, 0.018),
    RightEyeCornerTilt("RightEyeCornerTilt", FeatureGroup.EYE, 0.38, 0.018),
    EyeCornerTiltAsymmetry("EyeCornerTiltAsymmetry", FeatureGroup.EYE, 0.30, 0.020),
    InnerEyeNoseTipTriangle("InnerEyeNoseTipTriangle", FeatureGroup.MID_FACE, 0.38, 0.014),
    BrowNoseRootTriangle("BrowNoseRootTriangle", FeatureGroup.MID_FACE, 0.34, 0.014),
    NoseRootLateralOffset("NoseRootLateralOffset", FeatureGroup.MID_FACE, 0.34, 0.016),

    LeftTempleBrowDistance("LeftTempleBrowDistance", FeatureGroup.UPPER_FACE, 0.34, 0.016),
    RightTempleBrowDistance("RightTempleBrowDistance", FeatureGroup.UPPER_FACE, 0.34, 0.016),
    TempleBrowDistanceAsymmetry("TempleBrowDistanceAsymmetry", FeatureGroup.UPPER_FACE, 0.28, 0.018),
    ForeheadBrowTriangle("ForeheadBrowTriangle", FeatureGroup.UPPER_FACE, 0.32, 0.014),
    ForeheadEyeTriangle("ForeheadEyeTriangle", FeatureGroup.UPPER_FACE, 0.34, 0.014),
    UpperFaceTaper("UpperFaceTaper", FeatureGroup.UPPER_FACE, 0.32, 0.020),
    LeftBrowTempleSlope("LeftBrowTempleSlope", FeatureGroup.UPPER_FACE, 0.30, 0.035),
    RightBrowTempleSlope("RightBrowTempleSlope", FeatureGroup.UPPER_FACE, 0.30, 0.035),
    BrowTempleSlopeAsymmetry("BrowTempleSlopeAsymmetry", FeatureGroup.UPPER_FACE, 0.26, 0.030),
    LeftIrisEyeOffset("LeftIrisEyeOffset", FeatureGroup.EYE, 0.44, 0.018),
    RightIrisEyeOffset("RightIrisEyeOffset", FeatureGroup.EYE, 0.44, 0.018),
    IrisOffsetAsymmetry("IrisOffsetAsymmetry", FeatureGroup.EYE, 0.40, 0.020),
    IrisDistance("IrisDistance", FeatureGroup.EYE, 0.50, 0.016),
    LeftIrisNoseRoot("LeftIrisNoseRoot", FeatureGroup.EYE, 0.46, 0.018),
    RightIrisNoseRoot("RightIrisNoseRoot", FeatureGroup.EYE, 0.46, 0.018),
    IrisNoseRootAsymmetry("IrisNoseRootAsymmetry", FeatureGroup.EYE, 0.38, 0.020),
    IrisSpanRatio("IrisSpanRatio", FeatureGroup.EYE, 0.42, 0.020),
    EyeLineBrowLineGap("EyeLineBrowLineGap", FeatureGroup.UPPER_FACE, 0.42, 0.014),
    LeftOuterEyeNoseRoot("LeftOuterEyeNoseRoot", FeatureGroup.MID_FACE, 0.42, 0.014),
    RightOuterEyeNoseRoot("RightOuterEyeNoseRoot", FeatureGroup.MID_FACE, 0.42, 0.014),
    OuterEyeNoseRootAsymmetry("OuterEyeNoseRootAsymmetry", FeatureGroup.MID_FACE, 0.34, 0.016),
    LeftEyeForeheadDistance("LeftEyeForeheadDistance", FeatureGroup.UPPER_FACE, 0.38, 0.016),
    RightEyeForeheadDistance("RightEyeForeheadDistance", FeatureGroup.UPPER_FACE, 0.38, 0.016),
    EyeForeheadAsymmetry("EyeForeheadAsymmetry", FeatureGroup.UPPER_FACE, 0.30, 0.018),
    NoseRootForeheadDistance("NoseRootForeheadDistance", FeatureGroup.UPPER_FACE, 0.36, 0.016),
    UpperFaceDiagonalRatio("UpperFaceDiagonalRatio", FeatureGroup.UPPER_FACE, 0.34, 0.020),
    UpperFacePerimeterRatio("UpperFacePerimeterRatio", FeatureGroup.UPPER_FACE, 0.34, 0.020),
    LeftJawCheekDistance("LeftJawCheekDistance", FeatureGroup.LOWER_FACE, 0.36, 0.018),
    RightJawCheekDistance("RightJawCheekDistance", FeatureGroup.LOWER_FACE, 0.36, 0.018),
    JawCheekAsymmetry("JawCheekAsymmetry", FeatureGroup.LOWER_FACE, 0.30, 0.020),
    ChinLateralOffset("ChinLateralOffset", FeatureGroup.LOWER_FACE, 0.30, 0.020),
    LeftOrbitalTriangle("LeftOrbitalTriangle", FeatureGroup.UPPER_FACE, 0.36, 0.014),
    RightOrbitalTriangle("RightOrbitalTriangle", FeatureGroup.UPPER_FACE, 0.36, 0.014),
    OrbitalTriangleAsymmetry("OrbitalTriangleAsymmetry", FeatureGroup.UPPER_FACE, 0.30, 0.016),
    LeftInnerBrowNoseArea("LeftInnerBrowNoseArea", FeatureGroup.MID_FACE, 0.36, 0.014),
    RightInnerBrowNoseArea("RightInnerBrowNoseArea", FeatureGroup.MID_FACE, 0.36, 0.014),
    InnerBrowNoseAreaAsymmetry("InnerBrowNoseAreaAsymmetry", FeatureGroup.MID_FACE, 0.30, 0.016),
    BrowSpanEyeSpanRatio("BrowSpanEyeSpanRatio", FeatureGroup.UPPER_FACE, 0.34, 0.020),
    NoseRootToEyeSpanRatio("NoseRootToEyeSpanRatio", FeatureGroup.MID_FACE, 0.34, 0.018),
    NoseTipDepth("NoseTipDepth", FeatureGroup.MID_FACE, 0.32, 0.020),
    LeftEyeNoseDepth("LeftEyeNoseDepth", FeatureGroup.MID_FACE, 0.30, 0.020),
    RightEyeNoseDepth("RightEyeNoseDepth", FeatureGroup.MID_FACE, 0.30, 0.020),
    EyeNoseDepthAsymmetry("EyeNoseDepthAsymmetry", FeatureGroup.MID_FACE, 0.26, 0.022),
    LeftCheekNoseDepth("LeftCheekNoseDepth", FeatureGroup.MID_FACE, 0.28, 0.022),
    RightCheekNoseDepth("RightCheekNoseDepth", FeatureGroup.MID_FACE, 0.28, 0.022),
    CheekNoseDepthAsymmetry("CheekNoseDepthAsymmetry", FeatureGroup.MID_FACE, 0.24, 0.024),
    LeftForeheadTempleArea("LeftForeheadTempleArea", FeatureGroup.UPPER_FACE, 0.34, 0.014),
    RightForeheadTempleArea("RightForeheadTempleArea", FeatureGroup.UPPER_FACE, 0.34, 0.014),
    ForeheadTempleAreaAsymmetry("ForeheadTempleAreaAsymmetry", FeatureGroup.UPPER_FACE, 0.28, 0.016),
    LeftEyeBrowNoseTriangle("LeftEyeBrowNoseTriangle", FeatureGroup.MID_FACE, 0.34, 0.014),
    RightEyeBrowNoseTriangle("RightEyeBrowNoseTriangle", FeatureGroup.MID_FACE, 0.34, 0.014),
    EyeBrowNoseTriangleAsymmetry("EyeBrowNoseTriangleAsymmetry", FeatureGroup.MID_FACE, 0.28, 0.016),
    NoseBridgeEyeTriangle("NoseBridgeEyeTriangle", FeatureGroup.MID_FACE, 0.32, 0.014),
    NoseBridgeToEyeSpanRatio("NoseBridgeToEyeSpanRatio", FeatureGroup.MID_FACE, 0.32, 0.018),
    LeftUpperEyelidArch("LeftUpperEyelidArch", FeatureGroup.EYE, 0.32, 0.014),
    RightUpperEyelidArch("RightUpperEyelidArch", FeatureGroup.EYE, 0.32, 0.014),
    UpperEyelidArchAsymmetry("UpperEyelidArchAsymmetry", FeatureGroup.EYE, 0.28, 0.016),
    LeftLowerEyelidArch("LeftLowerEyelidArch", FeatureGroup.EYE, 0.32, 0.014),
    RightLowerEyelidArch("RightLowerEyelidArch", FeatureGroup.EYE, 0.32, 0.014),
    LowerEyelidArchAsymmetry("LowerEyelidArchAsymmetry", FeatureGroup.EYE, 0.28, 0.016),
    NoseBridgeBrowLineOffset("NoseBridgeBrowLineOffset", FeatureGroup.MID_FACE, 0.32, 0.014),
    NoseBridgeEyeLineOffset("NoseBridgeEyeLineOffset", FeatureGroup.MID_FACE, 0.32, 0.014),
    LeftInnerEyeNoseBridgeTriangle("LeftInnerEyeNoseBridgeTriangle", FeatureGroup.MID_FACE, 0.30, 0.014),
    RightInnerEyeNoseBridgeTriangle("RightInnerEyeNoseBridgeTriangle", FeatureGroup.MID_FACE, 0.30, 0.014),
    InnerEyeNoseBridgeTriangleAsymmetry("InnerEyeNoseBridgeTriangleAsymmetry", FeatureGroup.MID_FACE, 0.26, 0.016),
    NoseTipInnerEyeLineDistance("NoseTipInnerEyeLineDistance", FeatureGroup.MID_FACE, 0.30, 0.014),
    NoseBridgeInnerEyeSpanRatio("NoseBridgeInnerEyeSpanRatio", FeatureGroup.MID_FACE, 0.30, 0.018),
    NoseTipDepthToEyeSpanRatio("NoseTipDepthToEyeSpanRatio", FeatureGroup.MID_FACE, 0.28, 0.022);

    val isLowerFace: Boolean
        get() = group == FeatureGroup.LOWER_FACE

    val isMidFace: Boolean
        get() = group == FeatureGroup.MID_FACE

    val isEyeFeature: Boolean
        get() = group == FeatureGroup.EYE

    val isIrisFeature: Boolean
        get() = this == LeftIrisEyeOffset || this == RightIrisEyeOffset ||
            this == IrisOffsetAsymmetry || this == IrisDistance ||
            this == LeftIrisNoseRoot || this == RightIrisNoseRoot ||
            this == IrisNoseRootAsymmetry || this == IrisSpanRatio

    val isBrowOrNose: Boolean
        get() = this == BrowDistance || this == BrowWidth || this == BrowAsymmetry ||
            this == LeftBrowWidth || this == RightBrowWidth ||
            this == LeftBrowEyeGap || this == RightBrowEyeGap || this == BrowEyeGapAsymmetry ||
            this == LeftBrowOuterEyeGap || this == RightBrowOuterEyeGap || this == BrowOuterGapAsymmetry ||
            this == LeftBrowInnerEyeGap || this == RightBrowInnerEyeGap || this == BrowInnerGapAsymmetry ||
            this == InterBrowDistance || this == LeftBrowSlope || this == RightBrowSlope ||
            this == BrowSlopeAsymmetry || this == LeftBrowArchHeight || this == RightBrowArchHeight ||
            this == BrowArchAsymmetry || this == BrowLineTilt || this == LeftTempleBrowDistance ||
            this == RightTempleBrowDistance || this == TempleBrowDistanceAsymmetry ||
            this == ForeheadBrowTriangle || this == ForeheadEyeTriangle || this == UpperFaceTaper ||
            this == LeftBrowTempleSlope || this == RightBrowTempleSlope ||
            this == BrowTempleSlopeAsymmetry || this == EyeLineBrowLineGap ||
            this == LeftEyeForeheadDistance || this == RightEyeForeheadDistance ||
            this == EyeForeheadAsymmetry || this == NoseRootForeheadDistance ||
            this == UpperFaceDiagonalRatio || this == UpperFacePerimeterRatio ||
            this == LeftOrbitalTriangle || this == RightOrbitalTriangle ||
            this == OrbitalTriangleAsymmetry || this == BrowSpanEyeSpanRatio ||
            this == LeftForeheadTempleArea || this == RightForeheadTempleArea ||
            this == ForeheadTempleAreaAsymmetry ||
            this == NoseRootToBrowLine || group == FeatureGroup.MID_FACE

    val isUpperOrMidFace: Boolean
        get() = group == FeatureGroup.UPPER_FACE || group == FeatureGroup.MID_FACE

    val dependsOnLeftEye: Boolean
        get() = when (this) {
            EyeDistance,
            InnerEyeDistance,
            LeftEyeOpen,
            LeftEyeWidth,
            EyeOpenAsymmetry,
            EyeNoseLeft,
            EyeNoseSymmetry,
            LeftBrowEyeGap,
            BrowEyeGapAsymmetry,
            LeftUnderEyeCheek,
            UnderEyeCheekAsymmetry,
            LeftInnerEyeNoseRoot,
            InnerEyeNoseRootAsymmetry,
            LeftTempleEye,
            TempleEyeAsymmetry,
            EyeWidthAsymmetry,
            LeftEyeHeight,
            EyeHeightAsymmetry,
            LeftBrowOuterEyeGap,
            BrowOuterGapAsymmetry,
            LeftBrowInnerEyeGap,
            BrowInnerGapAsymmetry,
            ForeheadToEyeLine,
            LeftBrowEyeDistance,
            BrowEyeDistanceAsymmetry,
            NoseRootEyeLineDistance,
            NoseTipEyeLineDistance,
            NoseLateralOffset,
            LeftPeriocularArea,
            PeriocularAreaAsymmetry,
            LeftMidFaceTriangle,
            MidFaceTriangleAsymmetry,
            LeftUpperMidfaceArea,
            UpperMidfaceAreaAsymmetry,
            LeftEyeCornerTilt,
            EyeCornerTiltAsymmetry,
            InnerEyeNoseTipTriangle,
            LeftIrisEyeOffset,
            IrisOffsetAsymmetry,
            IrisDistance,
            LeftIrisNoseRoot,
            IrisNoseRootAsymmetry,
            IrisSpanRatio,
            EyeLineBrowLineGap,
            LeftOuterEyeNoseRoot,
            OuterEyeNoseRootAsymmetry,
            LeftEyeForeheadDistance,
            EyeForeheadAsymmetry,
            UpperFaceDiagonalRatio,
            UpperFacePerimeterRatio,
            LeftOrbitalTriangle,
            OrbitalTriangleAsymmetry,
            LeftInnerBrowNoseArea,
            InnerBrowNoseAreaAsymmetry,
            BrowSpanEyeSpanRatio,
            NoseRootToEyeSpanRatio,
            LeftEyeNoseDepth,
            EyeNoseDepthAsymmetry,
            LeftEyeBrowNoseTriangle,
            EyeBrowNoseTriangleAsymmetry,
            NoseBridgeEyeTriangle,
            NoseBridgeToEyeSpanRatio,
            LeftUpperEyelidArch,
            UpperEyelidArchAsymmetry,
            LeftLowerEyelidArch,
            LowerEyelidArchAsymmetry,
            NoseBridgeEyeLineOffset,
            LeftInnerEyeNoseBridgeTriangle,
            InnerEyeNoseBridgeTriangleAsymmetry,
            NoseTipInnerEyeLineDistance,
            NoseBridgeInnerEyeSpanRatio,
            NoseTipDepthToEyeSpanRatio -> true
            else -> false
        }

    val dependsOnRightEye: Boolean
        get() = when (this) {
            EyeDistance,
            InnerEyeDistance,
            RightEyeOpen,
            RightEyeWidth,
            EyeOpenAsymmetry,
            EyeNoseRight,
            EyeNoseSymmetry,
            RightBrowEyeGap,
            BrowEyeGapAsymmetry,
            RightUnderEyeCheek,
            UnderEyeCheekAsymmetry,
            RightInnerEyeNoseRoot,
            InnerEyeNoseRootAsymmetry,
            RightTempleEye,
            TempleEyeAsymmetry,
            EyeWidthAsymmetry,
            RightEyeHeight,
            EyeHeightAsymmetry,
            RightBrowOuterEyeGap,
            BrowOuterGapAsymmetry,
            RightBrowInnerEyeGap,
            BrowInnerGapAsymmetry,
            ForeheadToEyeLine,
            RightBrowEyeDistance,
            BrowEyeDistanceAsymmetry,
            NoseRootEyeLineDistance,
            NoseTipEyeLineDistance,
            NoseLateralOffset,
            RightPeriocularArea,
            PeriocularAreaAsymmetry,
            RightMidFaceTriangle,
            MidFaceTriangleAsymmetry,
            RightUpperMidfaceArea,
            UpperMidfaceAreaAsymmetry,
            RightEyeCornerTilt,
            EyeCornerTiltAsymmetry,
            InnerEyeNoseTipTriangle,
            RightIrisEyeOffset,
            IrisOffsetAsymmetry,
            IrisDistance,
            RightIrisNoseRoot,
            IrisNoseRootAsymmetry,
            IrisSpanRatio,
            EyeLineBrowLineGap,
            RightOuterEyeNoseRoot,
            OuterEyeNoseRootAsymmetry,
            RightEyeForeheadDistance,
            EyeForeheadAsymmetry,
            UpperFaceDiagonalRatio,
            UpperFacePerimeterRatio,
            RightOrbitalTriangle,
            OrbitalTriangleAsymmetry,
            RightInnerBrowNoseArea,
            InnerBrowNoseAreaAsymmetry,
            BrowSpanEyeSpanRatio,
            NoseRootToEyeSpanRatio,
            RightEyeNoseDepth,
            EyeNoseDepthAsymmetry,
            RightEyeBrowNoseTriangle,
            EyeBrowNoseTriangleAsymmetry,
            NoseBridgeEyeTriangle,
            NoseBridgeToEyeSpanRatio,
            RightUpperEyelidArch,
            UpperEyelidArchAsymmetry,
            RightLowerEyelidArch,
            LowerEyelidArchAsymmetry,
            NoseBridgeEyeLineOffset,
            RightInnerEyeNoseBridgeTriangle,
            InnerEyeNoseBridgeTriangleAsymmetry,
            NoseTipInnerEyeLineDistance,
            NoseBridgeInnerEyeSpanRatio,
            NoseTipDepthToEyeSpanRatio -> true
            else -> false
        }

    val isLeftEyeLocalFeature: Boolean
        get() = when (this) {
            LeftEyeOpen,
            LeftEyeWidth,
            LeftEyeHeight,
            EyeOpenAsymmetry,
            EyeHeightAsymmetry,
            EyeWidthAsymmetry,
            LeftBrowEyeDistance,
            BrowEyeDistanceAsymmetry,
            LeftPeriocularArea,
            PeriocularAreaAsymmetry,
            LeftUpperMidfaceArea,
            UpperMidfaceAreaAsymmetry,
            LeftEyeCornerTilt,
            EyeCornerTiltAsymmetry,
            LeftIrisEyeOffset,
            IrisOffsetAsymmetry,
            IrisDistance,
            LeftIrisNoseRoot,
            IrisNoseRootAsymmetry,
            IrisSpanRatio,
            LeftOrbitalTriangle,
            OrbitalTriangleAsymmetry,
            LeftInnerBrowNoseArea,
            InnerBrowNoseAreaAsymmetry,
            BrowSpanEyeSpanRatio,
            NoseRootToEyeSpanRatio,
            LeftEyeNoseDepth,
            EyeNoseDepthAsymmetry,
            LeftEyeBrowNoseTriangle,
            EyeBrowNoseTriangleAsymmetry,
            NoseBridgeEyeTriangle,
            NoseBridgeToEyeSpanRatio,
            LeftUpperEyelidArch,
            UpperEyelidArchAsymmetry,
            LeftLowerEyelidArch,
            LowerEyelidArchAsymmetry,
            NoseBridgeEyeLineOffset,
            LeftInnerEyeNoseBridgeTriangle,
            InnerEyeNoseBridgeTriangleAsymmetry,
            NoseTipInnerEyeLineDistance,
            NoseBridgeInnerEyeSpanRatio,
            NoseTipDepthToEyeSpanRatio -> true
            else -> false
        }

    val isRightEyeLocalFeature: Boolean
        get() = when (this) {
            RightEyeOpen,
            RightEyeWidth,
            RightEyeHeight,
            EyeOpenAsymmetry,
            EyeHeightAsymmetry,
            EyeWidthAsymmetry,
            RightBrowEyeDistance,
            BrowEyeDistanceAsymmetry,
            RightPeriocularArea,
            PeriocularAreaAsymmetry,
            RightUpperMidfaceArea,
            UpperMidfaceAreaAsymmetry,
            RightEyeCornerTilt,
            EyeCornerTiltAsymmetry,
            RightIrisEyeOffset,
            IrisOffsetAsymmetry,
            IrisDistance,
            RightIrisNoseRoot,
            IrisNoseRootAsymmetry,
            IrisSpanRatio,
            RightOrbitalTriangle,
            OrbitalTriangleAsymmetry,
            RightInnerBrowNoseArea,
            InnerBrowNoseAreaAsymmetry,
            BrowSpanEyeSpanRatio,
            NoseRootToEyeSpanRatio,
            RightEyeNoseDepth,
            EyeNoseDepthAsymmetry,
            RightEyeBrowNoseTriangle,
            EyeBrowNoseTriangleAsymmetry,
            NoseBridgeEyeTriangle,
            NoseBridgeToEyeSpanRatio,
            RightUpperEyelidArch,
            UpperEyelidArchAsymmetry,
            RightLowerEyelidArch,
            LowerEyelidArchAsymmetry,
            NoseBridgeEyeLineOffset,
            RightInnerEyeNoseBridgeTriangle,
            InnerEyeNoseBridgeTriangleAsymmetry,
            NoseTipInnerEyeLineDistance,
            NoseBridgeInnerEyeSpanRatio,
            NoseTipDepthToEyeSpanRatio -> true
            else -> false
        }

    companion object {
        val ordered: List<FeatureType> = entries.toList()
        val COUNT: Int = ordered.size
    }
}
