package dev.andface.galaxy

import dev.andface.galaxy.feature.FeatureType
import kotlin.math.abs
import kotlin.math.max

internal fun completeFeatureVector(vararg baseValues: Double): DoubleArray {
    require(baseValues.size <= FeatureType.COUNT) {
        "feature vector has ${baseValues.size} values but FeatureType.COUNT is ${FeatureType.COUNT}"
    }

    val values = DoubleArray(FeatureType.COUNT) { index ->
        if (index < baseValues.size) baseValues[index] else 0.0
    }
    if (baseValues.size <= FeatureType.UnderEyeCheekAsymmetry.ordinal) return values

    fun value(type: FeatureType): Double = values[type.ordinal]
    fun put(type: FeatureType, value: Double) {
        values[type.ordinal] = value
    }

    val eyeDistance = value(FeatureType.EyeDistance)
    val browDistance = value(FeatureType.BrowDistance)
    val innerEyeDistance = value(FeatureType.InnerEyeDistance)
    val noseBridge = value(FeatureType.NoseBridgeLength)
    val browAsymmetry = value(FeatureType.BrowAsymmetry)
    val eyeNoseSymmetry = value(FeatureType.EyeNoseSymmetry)
    val upperFaceWidth = value(FeatureType.UpperFaceWidth)
    val leftEyeWidth = value(FeatureType.LeftEyeWidth)
    val rightEyeWidth = value(FeatureType.RightEyeWidth)
    val leftEyeOpen = value(FeatureType.LeftEyeOpen)
    val rightEyeOpen = value(FeatureType.RightEyeOpen)
    val leftCheekNose = value(FeatureType.LeftCheekNose)
    val rightCheekNose = value(FeatureType.RightCheekNose)
    val leftUnderEyeCheek = value(FeatureType.LeftUnderEyeCheek)
    val rightUnderEyeCheek = value(FeatureType.RightUnderEyeCheek)
    val noseWidth = value(FeatureType.NoseWidth)
    val noseToChin = value(FeatureType.NoseToChin)
    val mouthWidth = value(FeatureType.MouthWidth)
    val noseToMouth = value(FeatureType.NoseToMouth)
    val faceAspect = value(FeatureType.FaceAspect)

    val eyeCenterDistance = max(eyeDistance, 1.0e-6)
    val leftIrisEyeOffset = 0.0
    val rightIrisEyeOffset = 0.0
    val irisDistance = eyeDistance
    val leftIrisNoseRoot = (innerEyeDistance * 0.72 + noseBridge * 0.18).coerceIn(0.03, 0.62)
    val rightIrisNoseRoot = (innerEyeDistance * 0.72 + noseBridge * 0.18 + eyeNoseSymmetry * 0.05).coerceIn(0.03, 0.62)

    val leftBrowNoseRoot = (browDistance + noseBridge * 0.55 + browAsymmetry * 0.18).coerceIn(0.03, 0.48)
    val rightBrowNoseRoot = (browDistance + noseBridge * 0.55 + eyeNoseSymmetry * 0.16).coerceIn(0.03, 0.48)
    val leftInnerEyeNoseRoot = (innerEyeDistance * 0.45 + eyeNoseSymmetry * 0.04).coerceIn(0.02, 0.36)
    val rightInnerEyeNoseRoot = (innerEyeDistance * 0.46 + browAsymmetry * 0.04).coerceIn(0.02, 0.36)
    val leftTempleEye = ((upperFaceWidth - eyeDistance).coerceAtLeast(0.05) * 0.55 + browAsymmetry * 0.12)
        .coerceIn(0.03, 0.58)
    val rightTempleEye = ((upperFaceWidth - eyeDistance).coerceAtLeast(0.05) * 0.55 + eyeNoseSymmetry * 0.10)
        .coerceIn(0.03, 0.58)
    val leftBrowSlope = (browAsymmetry * 0.65).coerceIn(0.0, 0.85)
    val rightBrowSlope = (eyeNoseSymmetry * 0.55).coerceIn(0.0, 0.85)
    val leftEyeHeight = (leftEyeOpen * leftEyeWidth * 2.0).coerceIn(0.02, 0.20)
    val rightEyeHeight = (rightEyeOpen * rightEyeWidth * 2.0).coerceIn(0.02, 0.20)
    val leftBrowWidth = (value(FeatureType.BrowWidth) + browAsymmetry * 0.5).coerceIn(0.03, 0.34)
    val rightBrowWidth = (value(FeatureType.BrowWidth) - browAsymmetry * 0.5).coerceIn(0.03, 0.34)
    val leftBrowOuterEyeGap = (browDistance * 1.18 + browAsymmetry * 0.08).coerceIn(0.02, 0.42)
    val rightBrowOuterEyeGap = (browDistance * 1.16 + eyeNoseSymmetry * 0.08).coerceIn(0.02, 0.42)
    val leftBrowInnerEyeGap = (browDistance * 1.04 + browAsymmetry * 0.06).coerceIn(0.02, 0.42)
    val rightBrowInnerEyeGap = (browDistance * 1.03 + eyeNoseSymmetry * 0.06).coerceIn(0.02, 0.42)

    put(FeatureType.InterBrowDistance, (eyeDistance * 0.82 + browAsymmetry * 0.15).coerceIn(0.05, 0.70))
    put(FeatureType.LeftBrowNoseRoot, leftBrowNoseRoot)
    put(FeatureType.RightBrowNoseRoot, rightBrowNoseRoot)
    put(FeatureType.BrowNoseRootAsymmetry, abs(leftBrowNoseRoot - rightBrowNoseRoot))
    put(FeatureType.LeftInnerEyeNoseRoot, leftInnerEyeNoseRoot)
    put(FeatureType.RightInnerEyeNoseRoot, rightInnerEyeNoseRoot)
    put(FeatureType.InnerEyeNoseRootAsymmetry, abs(leftInnerEyeNoseRoot - rightInnerEyeNoseRoot))
    put(FeatureType.LeftTempleEye, leftTempleEye)
    put(FeatureType.RightTempleEye, rightTempleEye)
    put(FeatureType.TempleEyeAsymmetry, abs(leftTempleEye - rightTempleEye))
    put(FeatureType.EyeWidthAsymmetry, abs(leftEyeWidth - rightEyeWidth) / max((leftEyeWidth + rightEyeWidth) * 0.5, 1.0e-6))
    put(FeatureType.LeftBrowSlope, leftBrowSlope)
    put(FeatureType.RightBrowSlope, rightBrowSlope)
    put(FeatureType.BrowSlopeAsymmetry, abs(leftBrowSlope - rightBrowSlope))
    put(FeatureType.LeftEyeHeight, leftEyeHeight)
    put(FeatureType.RightEyeHeight, rightEyeHeight)
    put(
        FeatureType.EyeHeightAsymmetry,
        abs(leftEyeHeight - rightEyeHeight) / max((leftEyeHeight + rightEyeHeight) * 0.5, 1.0e-6)
    )
    put(FeatureType.LeftBrowWidth, leftBrowWidth)
    put(FeatureType.RightBrowWidth, rightBrowWidth)
    put(FeatureType.LeftBrowOuterEyeGap, leftBrowOuterEyeGap)
    put(FeatureType.RightBrowOuterEyeGap, rightBrowOuterEyeGap)
    put(FeatureType.BrowOuterGapAsymmetry, abs(leftBrowOuterEyeGap - rightBrowOuterEyeGap))
    put(FeatureType.LeftBrowInnerEyeGap, leftBrowInnerEyeGap)
    put(FeatureType.RightBrowInnerEyeGap, rightBrowInnerEyeGap)
    put(FeatureType.BrowInnerGapAsymmetry, abs(leftBrowInnerEyeGap - rightBrowInnerEyeGap))
    put(FeatureType.NoseRootToBrowLine, (browDistance + noseBridge * 0.10).coerceIn(0.02, 0.48))
    put(FeatureType.ForeheadToEyeLine, (0.20 + noseBridge * 0.36 + browDistance * 0.15).coerceIn(0.12, 0.70))
    put(FeatureType.UpperFaceAspect, ((noseBridge / max(upperFaceWidth, 1.0e-6)) * 1.70).coerceIn(0.12, 1.10))
    val leftBrowEyeDistance = (browDistance * 1.50 + leftEyeHeight * 0.15).coerceIn(0.03, 0.42)
    val rightBrowEyeDistance = (browDistance * 1.48 + rightEyeHeight * 0.15 + eyeNoseSymmetry * 0.03).coerceIn(0.03, 0.42)
    val noseRootEyeLineDistance = (eyeNoseSymmetry * 0.10 + browAsymmetry * 0.03).coerceIn(0.0, 0.22)
    val noseTipEyeLineDistance = (noseBridge * 0.86 + browDistance * 0.34).coerceIn(0.08, 0.48)
    val noseLateralOffset = (eyeNoseSymmetry * 0.45 + browAsymmetry * 0.08).coerceIn(0.0, 0.24)
    val leftPeriocularArea = (leftEyeWidth * leftBrowEyeDistance * 0.50).coerceIn(0.002, 0.08)
    val rightPeriocularArea = (rightEyeWidth * rightBrowEyeDistance * 0.50).coerceIn(0.002, 0.08)
    val leftMidFaceTriangle = (leftCheekNose * noseBridge * 0.55).coerceIn(0.010, 0.18)
    val rightMidFaceTriangle = (rightCheekNose * (noseBridge + eyeNoseSymmetry * 0.10) * 0.55).coerceIn(0.010, 0.18)
    val leftUpperMidfaceArea = (leftEyeWidth * leftUnderEyeCheek * 0.18).coerceIn(0.002, 0.18)
    val rightUpperMidfaceArea = (rightEyeWidth * rightUnderEyeCheek * 0.18).coerceIn(0.002, 0.18)
    val leftNoseCheekArea = (leftCheekNose * noseBridge * 0.50).coerceIn(0.002, 0.18)
    val rightNoseCheekArea = (rightCheekNose * (noseBridge + eyeNoseSymmetry * 0.10) * 0.50).coerceIn(0.002, 0.18)
    val leftTempleCheekSlope = (leftUnderEyeCheek / max(leftTempleEye + leftUnderEyeCheek, 1.0e-6) * 1.55).coerceIn(0.0, 1.0)
    val rightTempleCheekSlope = (rightUnderEyeCheek / max(rightTempleEye + rightUnderEyeCheek, 1.0e-6) * 1.55).coerceIn(0.0, 1.0)
    val midfaceWidthRatio = (value(FeatureType.CheekboneWidth) / max(upperFaceWidth, 1.0e-6)).coerceIn(0.35, 1.35)
    val leftBrowArchHeight = (browDistance * 0.45 + browAsymmetry * 0.05).coerceIn(0.0, 0.16)
    val rightBrowArchHeight = (browDistance * 0.44 + eyeNoseSymmetry * 0.05).coerceIn(0.0, 0.16)
    val browLineTilt = ((browAsymmetry + eyeNoseSymmetry) * 0.30).coerceIn(0.0, 0.65)
    val leftEyeCornerTilt = (leftEyeHeight / max(leftEyeWidth, 1.0e-6) * 0.08 + browAsymmetry * 0.04)
        .coerceIn(0.0, 0.80)
    val rightEyeCornerTilt = (rightEyeHeight / max(rightEyeWidth, 1.0e-6) * 0.08 + eyeNoseSymmetry * 0.04)
        .coerceIn(0.0, 0.80)
    val innerEyeNoseTipTriangle = (innerEyeDistance * noseBridge * 0.30).coerceIn(0.0, 0.14)
    val browNoseRootTriangle = (eyeDistance * browDistance * 0.18 + noseBridge * 0.005).coerceIn(0.0, 0.10)
    val noseRootLateralOffset = (eyeNoseSymmetry * 0.25 + browAsymmetry * 0.04).coerceIn(0.0, 0.24)
    val leftTempleBrowDistance = (leftTempleEye * 0.75 + leftBrowWidth * 0.35).coerceIn(0.03, 0.68)
    val rightTempleBrowDistance = (rightTempleEye * 0.75 + rightBrowWidth * 0.35).coerceIn(0.03, 0.68)
    val foreheadBrowTriangle = (upperFaceWidth * browDistance * 0.34).coerceIn(0.0, 0.16)
    val foreheadEyeTriangle = (upperFaceWidth * (browDistance + leftEyeHeight + rightEyeHeight) * 0.22).coerceIn(0.0, 0.20)
    val upperFaceTaper = (value(FeatureType.InterBrowDistance) / max(upperFaceWidth, 1.0e-6)).coerceIn(0.18, 1.05)
    val leftBrowTempleSlope = (leftBrowSlope * 0.50 + leftTempleCheekSlope * 0.18).coerceIn(0.0, 1.05)
    val rightBrowTempleSlope = (rightBrowSlope * 0.50 + rightTempleCheekSlope * 0.18).coerceIn(0.0, 1.05)
    put(FeatureType.LeftBrowEyeDistance, leftBrowEyeDistance)
    put(FeatureType.RightBrowEyeDistance, rightBrowEyeDistance)
    put(FeatureType.BrowEyeDistanceAsymmetry, abs(leftBrowEyeDistance - rightBrowEyeDistance))
    put(FeatureType.NoseRootEyeLineDistance, noseRootEyeLineDistance)
    put(FeatureType.NoseTipEyeLineDistance, noseTipEyeLineDistance)
    put(FeatureType.NoseLateralOffset, noseLateralOffset)
    put(FeatureType.LeftPeriocularArea, leftPeriocularArea)
    put(FeatureType.RightPeriocularArea, rightPeriocularArea)
    put(FeatureType.PeriocularAreaAsymmetry, abs(leftPeriocularArea - rightPeriocularArea))
    put(FeatureType.LeftMidFaceTriangle, leftMidFaceTriangle)
    put(FeatureType.RightMidFaceTriangle, rightMidFaceTriangle)
    put(FeatureType.MidFaceTriangleAsymmetry, abs(leftMidFaceTriangle - rightMidFaceTriangle))
    put(FeatureType.LeftUpperMidfaceArea, leftUpperMidfaceArea)
    put(FeatureType.RightUpperMidfaceArea, rightUpperMidfaceArea)
    put(FeatureType.UpperMidfaceAreaAsymmetry, abs(leftUpperMidfaceArea - rightUpperMidfaceArea))
    put(FeatureType.LeftNoseCheekArea, leftNoseCheekArea)
    put(FeatureType.RightNoseCheekArea, rightNoseCheekArea)
    put(FeatureType.NoseCheekAreaAsymmetry, abs(leftNoseCheekArea - rightNoseCheekArea))
    put(FeatureType.LeftTempleCheekSlope, leftTempleCheekSlope)
    put(FeatureType.RightTempleCheekSlope, rightTempleCheekSlope)
    put(FeatureType.TempleCheekSlopeAsymmetry, abs(leftTempleCheekSlope - rightTempleCheekSlope))
    put(FeatureType.MidfaceWidthRatio, midfaceWidthRatio)
    put(FeatureType.LeftBrowArchHeight, leftBrowArchHeight)
    put(FeatureType.RightBrowArchHeight, rightBrowArchHeight)
    put(FeatureType.BrowArchAsymmetry, abs(leftBrowArchHeight - rightBrowArchHeight))
    put(FeatureType.BrowLineTilt, browLineTilt)
    put(FeatureType.LeftEyeCornerTilt, leftEyeCornerTilt)
    put(FeatureType.RightEyeCornerTilt, rightEyeCornerTilt)
    put(FeatureType.EyeCornerTiltAsymmetry, abs(leftEyeCornerTilt - rightEyeCornerTilt))
    put(FeatureType.InnerEyeNoseTipTriangle, innerEyeNoseTipTriangle)
    put(FeatureType.BrowNoseRootTriangle, browNoseRootTriangle)
    put(FeatureType.NoseRootLateralOffset, noseRootLateralOffset)
    put(FeatureType.LeftTempleBrowDistance, leftTempleBrowDistance)
    put(FeatureType.RightTempleBrowDistance, rightTempleBrowDistance)
    put(FeatureType.TempleBrowDistanceAsymmetry, abs(leftTempleBrowDistance - rightTempleBrowDistance))
    put(FeatureType.ForeheadBrowTriangle, foreheadBrowTriangle)
    put(FeatureType.ForeheadEyeTriangle, foreheadEyeTriangle)
    put(FeatureType.UpperFaceTaper, upperFaceTaper)
    put(FeatureType.LeftBrowTempleSlope, leftBrowTempleSlope)
    put(FeatureType.RightBrowTempleSlope, rightBrowTempleSlope)
    put(FeatureType.BrowTempleSlopeAsymmetry, abs(leftBrowTempleSlope - rightBrowTempleSlope))
    val leftNoseWing = (noseWidth * 0.52 + eyeNoseSymmetry * 0.04).coerceIn(0.02, 0.36)
    val rightNoseWing = (noseWidth * 0.52 + browAsymmetry * 0.04).coerceIn(0.02, 0.36)
    val noseBaseTriangle = (noseWidth * noseBridge * 0.08).coerceIn(0.001, 0.08)
    val mouthHeight = (mouthWidth * 0.22).coerceIn(0.01, 0.20)
    val mouthAspect = (mouthHeight / max(mouthWidth, 1.0e-6)).coerceIn(0.02, 1.20)
    val chinMouthDistance = (noseToChin - noseToMouth).coerceIn(0.02, 0.70)
    val chinJawOffset = (noseToChin * 0.72 + faceAspect * 0.04).coerceIn(0.10, 0.90)
    put(FeatureType.LeftNoseWing, leftNoseWing)
    put(FeatureType.RightNoseWing, rightNoseWing)
    put(FeatureType.NoseWingAsymmetry, abs(leftNoseWing - rightNoseWing))
    put(FeatureType.NoseBaseTriangle, noseBaseTriangle)
    put(FeatureType.MouthHeight, mouthHeight)
    put(FeatureType.MouthAspect, mouthAspect)
    put(FeatureType.ChinMouthDistance, chinMouthDistance)
    put(FeatureType.ChinJawOffset, chinJawOffset)
    put(FeatureType.LeftIrisEyeOffset, leftIrisEyeOffset)
    put(FeatureType.RightIrisEyeOffset, rightIrisEyeOffset)
    put(FeatureType.IrisOffsetAsymmetry, abs(leftIrisEyeOffset - rightIrisEyeOffset))
    put(FeatureType.IrisDistance, irisDistance.coerceIn(0.15, 0.78))
    put(FeatureType.LeftIrisNoseRoot, leftIrisNoseRoot)
    put(FeatureType.RightIrisNoseRoot, rightIrisNoseRoot)
    put(FeatureType.IrisNoseRootAsymmetry, abs(leftIrisNoseRoot - rightIrisNoseRoot))
    put(FeatureType.IrisSpanRatio, (irisDistance / eyeCenterDistance).coerceIn(0.45, 1.35))
    val eyeLineBrowLineGap = (browDistance * 1.50).coerceIn(0.02, 0.42)
    val leftOuterEyeNoseRoot = (eyeDistance * 0.55 + noseBridge * 0.08 + browAsymmetry * 0.04).coerceIn(0.03, 0.62)
    val rightOuterEyeNoseRoot = (eyeDistance * 0.55 + noseBridge * 0.08 + eyeNoseSymmetry * 0.04).coerceIn(0.03, 0.62)
    val leftEyeForeheadDistance = (0.20 + noseBridge * 0.45 + browDistance * 0.80).coerceIn(0.12, 0.90)
    val rightEyeForeheadDistance = (0.20 + noseBridge * 0.45 + browDistance * 0.78 + eyeNoseSymmetry * 0.04).coerceIn(0.12, 0.90)
    val noseRootForeheadDistance = (0.18 + noseBridge * 0.60).coerceIn(0.08, 0.75)
    val upperFaceDiagonalRatio = (upperFaceWidth * 0.70 + eyeDistance * 0.10).coerceIn(0.25, 1.25)
    val upperFacePerimeterRatio = (upperFaceWidth * 0.75 + browDistance * 1.40 + noseBridge * 0.35).coerceIn(0.30, 1.50)
    val leftJawCheekDistance = (noseToChin * 0.18 + faceAspect * 0.025 + browAsymmetry * 0.04).coerceIn(0.03, 0.45)
    val rightJawCheekDistance = (noseToChin * 0.18 + faceAspect * 0.025 + eyeNoseSymmetry * 0.04).coerceIn(0.03, 0.45)
    put(FeatureType.EyeLineBrowLineGap, eyeLineBrowLineGap)
    put(FeatureType.LeftOuterEyeNoseRoot, leftOuterEyeNoseRoot)
    put(FeatureType.RightOuterEyeNoseRoot, rightOuterEyeNoseRoot)
    put(FeatureType.OuterEyeNoseRootAsymmetry, abs(leftOuterEyeNoseRoot - rightOuterEyeNoseRoot))
    put(FeatureType.LeftEyeForeheadDistance, leftEyeForeheadDistance)
    put(FeatureType.RightEyeForeheadDistance, rightEyeForeheadDistance)
    put(FeatureType.EyeForeheadAsymmetry, abs(leftEyeForeheadDistance - rightEyeForeheadDistance))
    put(FeatureType.NoseRootForeheadDistance, noseRootForeheadDistance)
    put(FeatureType.UpperFaceDiagonalRatio, upperFaceDiagonalRatio)
    put(FeatureType.UpperFacePerimeterRatio, upperFacePerimeterRatio)
    put(FeatureType.LeftJawCheekDistance, leftJawCheekDistance)
    put(FeatureType.RightJawCheekDistance, rightJawCheekDistance)
    put(FeatureType.JawCheekAsymmetry, abs(leftJawCheekDistance - rightJawCheekDistance))
    put(FeatureType.ChinLateralOffset, (eyeNoseSymmetry * 0.32 + browAsymmetry * 0.08).coerceIn(0.0, 0.24))
    val leftOrbitalTriangle = (leftTempleEye * leftBrowEyeDistance * 0.22).coerceIn(0.0, 0.12)
    val rightOrbitalTriangle = (rightTempleEye * rightBrowEyeDistance * 0.22).coerceIn(0.0, 0.12)
    val leftInnerBrowNoseArea = (leftInnerEyeNoseRoot * leftBrowNoseRoot * 0.18).coerceIn(0.0, 0.10)
    val rightInnerBrowNoseArea = (rightInnerEyeNoseRoot * rightBrowNoseRoot * 0.18).coerceIn(0.0, 0.10)
    put(FeatureType.LeftOrbitalTriangle, leftOrbitalTriangle)
    put(FeatureType.RightOrbitalTriangle, rightOrbitalTriangle)
    put(FeatureType.OrbitalTriangleAsymmetry, abs(leftOrbitalTriangle - rightOrbitalTriangle))
    put(FeatureType.LeftInnerBrowNoseArea, leftInnerBrowNoseArea)
    put(FeatureType.RightInnerBrowNoseArea, rightInnerBrowNoseArea)
    put(FeatureType.InnerBrowNoseAreaAsymmetry, abs(leftInnerBrowNoseArea - rightInnerBrowNoseArea))
    put(FeatureType.BrowSpanEyeSpanRatio, (value(FeatureType.InterBrowDistance) / eyeCenterDistance).coerceIn(0.40, 1.40))
    put(FeatureType.NoseRootToEyeSpanRatio, (noseRootEyeLineDistance / eyeCenterDistance).coerceIn(0.0, 0.50))
    val noseTipDepth = (noseBridge * 0.22 + noseWidth * 0.05).coerceIn(0.0, 0.50)
    val leftEyeNoseDepth = (noseTipDepth + leftInnerEyeNoseRoot * 0.16).coerceIn(0.0, 0.60)
    val rightEyeNoseDepth = (noseTipDepth + rightInnerEyeNoseRoot * 0.16 + eyeNoseSymmetry * 0.04).coerceIn(0.0, 0.60)
    val leftCheekNoseDepth = (noseTipDepth + leftCheekNose * 0.08).coerceIn(0.0, 0.65)
    val rightCheekNoseDepth = (noseTipDepth + rightCheekNose * 0.08 + eyeNoseSymmetry * 0.03).coerceIn(0.0, 0.65)
    put(FeatureType.NoseTipDepth, noseTipDepth)
    put(FeatureType.LeftEyeNoseDepth, leftEyeNoseDepth)
    put(FeatureType.RightEyeNoseDepth, rightEyeNoseDepth)
    put(FeatureType.EyeNoseDepthAsymmetry, abs(leftEyeNoseDepth - rightEyeNoseDepth))
    put(FeatureType.LeftCheekNoseDepth, leftCheekNoseDepth)
    put(FeatureType.RightCheekNoseDepth, rightCheekNoseDepth)
    put(FeatureType.CheekNoseDepthAsymmetry, abs(leftCheekNoseDepth - rightCheekNoseDepth))
    val leftForeheadTempleArea = (leftTempleBrowDistance * browDistance * 0.18).coerceIn(0.0, 0.18)
    val rightForeheadTempleArea = (rightTempleBrowDistance * browDistance * 0.18).coerceIn(0.0, 0.18)
    val leftEyeBrowNoseTriangle = (leftBrowEyeDistance * leftInnerEyeNoseRoot * 0.36).coerceIn(0.0, 0.12)
    val rightEyeBrowNoseTriangle = (rightBrowEyeDistance * rightInnerEyeNoseRoot * 0.36).coerceIn(0.0, 0.12)
    val noseBridgeEyeTriangle = (eyeDistance * noseRootEyeLineDistance * 0.50).coerceIn(0.0, 0.12)
    put(FeatureType.LeftForeheadTempleArea, leftForeheadTempleArea)
    put(FeatureType.RightForeheadTempleArea, rightForeheadTempleArea)
    put(FeatureType.ForeheadTempleAreaAsymmetry, abs(leftForeheadTempleArea - rightForeheadTempleArea))
    put(FeatureType.LeftEyeBrowNoseTriangle, leftEyeBrowNoseTriangle)
    put(FeatureType.RightEyeBrowNoseTriangle, rightEyeBrowNoseTriangle)
    put(FeatureType.EyeBrowNoseTriangleAsymmetry, abs(leftEyeBrowNoseTriangle - rightEyeBrowNoseTriangle))
    put(FeatureType.NoseBridgeEyeTriangle, noseBridgeEyeTriangle)
    put(FeatureType.NoseBridgeToEyeSpanRatio, (noseBridge / eyeCenterDistance).coerceIn(0.05, 1.80))
    val leftInnerEyeNoseBridgeTriangle = (leftInnerEyeNoseRoot * noseBridge * 0.32).coerceIn(0.0, 0.12)
    val rightInnerEyeNoseBridgeTriangle = (rightInnerEyeNoseRoot * noseBridge * 0.32).coerceIn(0.0, 0.12)
    put(FeatureType.LeftInnerEyeNoseBridgeTriangle, leftInnerEyeNoseBridgeTriangle)
    put(FeatureType.RightInnerEyeNoseBridgeTriangle, rightInnerEyeNoseBridgeTriangle)
    put(
        FeatureType.InnerEyeNoseBridgeTriangleAsymmetry,
        abs(leftInnerEyeNoseBridgeTriangle - rightInnerEyeNoseBridgeTriangle)
    )
    put(FeatureType.NoseTipInnerEyeLineDistance, noseTipEyeLineDistance.coerceIn(0.06, 0.52))
    put(FeatureType.NoseBridgeInnerEyeSpanRatio, (noseBridge / max(innerEyeDistance, 1.0e-6)).coerceIn(0.05, 1.80))
    put(FeatureType.NoseTipDepthToEyeSpanRatio, (noseTipDepth / max(innerEyeDistance, 1.0e-6)).coerceIn(0.0, 0.80))
    val leftUpperEyelidArch = (leftEyeHeight * 0.50).coerceIn(0.0, 0.20)
    val rightUpperEyelidArch = (rightEyeHeight * 0.50).coerceIn(0.0, 0.20)
    val leftLowerEyelidArch = (leftEyeHeight * 0.50).coerceIn(0.0, 0.20)
    val rightLowerEyelidArch = (rightEyeHeight * 0.50).coerceIn(0.0, 0.20)
    put(FeatureType.LeftUpperEyelidArch, leftUpperEyelidArch)
    put(FeatureType.RightUpperEyelidArch, rightUpperEyelidArch)
    put(FeatureType.UpperEyelidArchAsymmetry, abs(leftUpperEyelidArch - rightUpperEyelidArch))
    put(FeatureType.LeftLowerEyelidArch, leftLowerEyelidArch)
    put(FeatureType.RightLowerEyelidArch, rightLowerEyelidArch)
    put(FeatureType.LowerEyelidArchAsymmetry, abs(leftLowerEyelidArch - rightLowerEyelidArch))
    put(FeatureType.NoseBridgeBrowLineOffset, browDistance.coerceIn(0.0, 0.35))
    put(FeatureType.NoseBridgeEyeLineOffset, noseRootEyeLineDistance.coerceIn(0.0, 0.35))

    return values
}

